"""
This is the script for dimensionality reduction for structures generated by ESM0fold.
The structures are represented as a 3D tensor, and the dimensionality reduction is done using PCA.
The reduced dimensions are then used to visualize the structures in 2D space using UMAP.
The script also saves the reduced dimensions and the UMAP coordinates in a file.

Peter Vallet 2024
"""

import argparse
import os
import pickle
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA, _incremental_pca

# Parse the arguments
parser = argparse.ArgumentParser(description="This script is used to perform dimensionality reduction on the structures generated by ESM0fold")
parser.add_argument("structures", help="The path to the structures folder")
parser.add_argument("output", help="The path to the output file")
args = parser.parse_args()


# Load the structures
variants = []
for file in os.listdir(args.structures):
    if file.endswith(".pkl"):
        with open(os.path.join(args.structures, file), "rb") as f:
            structure = pickle.load(f)
            variants.append(structure)

# This would be calculation of PCA for all individual samples

# pca_dict = {}
# # get positions of atoms
# for group in variants:
#     # Assuming `atom_positions` is your 3D tensor
#     pca = PCA(n_components=10)  # Reduce to 10 dimensions
#     reduced_positions = pca.fit_transform(group.positions)
#     pca_dict.update({"variant": group.variants, "pca_10": reduced_positions})

# This would be calculation of PCA for the whole data through mini-batch PCA
transformer = IncrementalPCA(n_components=10, batch_size=5)
# either partially fit on smaller batches of data
transformer.partial_fit(variants[0:5].positions).
IncrementalPCA(batch_size=200, n_components=10)
# or let the fit function itself divide the data into batches
X_sparse = sparse.csr_matrix(X)
X_transformed = transformer.fit_transform(X_sparse)
X_transformed.shape
