"""
This is the script for dimensionality reduction for structures generated by ESM0fold.
The structures are represented as a 3D tensor, and the dimensionality reduction is done using PCA.
The reduced dimensions are then used to visualize the structures in 2D space using UMAP.
The script also saves the reduced dimensions and the UMAP coordinates in a file.

Peter Vallet 2024
"""

import argparse
import os
import numpy as np
import pickle
from sklearn.decomposition import IncrementalPCA, PCA

# Parse the arguments
parser = argparse.ArgumentParser(description="This script is used to perform dimensionality "
                                             "reduction on the structures generated by ESM0fold")
parser.add_argument("structures", help="The path to the structures folder")
parser.add_argument("output", help="The path to the output file")
args = parser.parse_args()

# Load the structures
pca_dict = {}
for file in os.listdir(args.structures):
    with open(os.path.join(args.structures, file), "rb") as f:
        structure = pickle.load(f)
        variant = list(structure.keys())[0]
        pca_dict.update({variant: {"AtomicPos": structure[variant]["Structure"]["positions"], "Fitness": structure[variant]["Fitness"]}})

# for file in os.listdir(fpath):
#     with open(os.path.join(fpath, file), "rb") as f:
#         structure = pickle.load(f)
#         variant = list(structure.keys())[0]
#         pca_dict.update({variant: {"AtomicPos": structure[variant]["Structure"]["positions"], "Fitness": structure[variant]["Fitness"]}})


# This would be calculation of PCA for the whole data through mini-batch PCA
# ipca = IncrementalPCA(n_components=10, batch_size=5)
# either partially fit on smaller batches of data
n_components = 10  # Choose an appropriate value
pca = PCA(n_components=n_components)
variant_list = list(pca_dict.keys())
red_pos = dict()
for variant in variant_list:
    flattened_positions = pca_dict[variant]["AtomicPos"].reshape(pca_dict[variant]["AtomicPos"].shape[0], -1)
    red_pos.update({variant: {"PCA": pca.fit_transform(flattened_positions)}})


