"""
This is the script for dimensionality reduction for structures generated by ESM0fold.
The structures are represented as a 3D tensor, and the dimensionality reduction is done using PCA.
The reduced dimensions are then used to visualize the structures in 2D space using UMAP.
The script also saves the reduced dimensions and the UMAP coordinates in a file.

Peter Vallet 2024
"""

import argparse
import os
import pickle
from sklearn.decomposition import IncrementalPCA

# Parse the arguments
parser = argparse.ArgumentParser(description="This script is used to perform dimensionality "
                                             "reduction on the structures generated by ESM0fold")
parser.add_argument("structures", help="The path to the structures folder")
parser.add_argument("output", help="The path to the output file")
args = parser.parse_args()

# Load the structures
pca_dict = {}
for file in os.listdir(args.structures):
    with open(os.path.join(args.structures, file), "rb") as f:
        structure = pickle.load(f)
        pca_dict.update({"variant": structure.keys()[0],
                         "AtomicPos": structure["Structure"]["positions"], "Fitness": structure["Fitness"]})

# This would be calculation of PCA for the whole data through mini-batch PCA
transformer = IncrementalPCA(n_components=10, batch_size=5)
# either partially fit on smaller batches of data
transformer.partial_fit(pca_dict[0:5].positions)
IncrementalPCA(batch_size=200, n_components=10)
